/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Hasher {
  constructor()
  static newKeyed(key: Uint8Array): Hasher
  update(data: Uint8Array): void
  updateRayon(data: Uint8Array): void
  finalize(): Array<number>
  finalizeXof(outLen: number): Array<number>
  reset(): void
}

export declare function deriveKey(context: string, keyMaterial: Uint8Array): Array<number>

export declare function hash(data: Uint8Array): Array<number>

export declare function hashRayon(data: Uint8Array): Array<number>

export declare function hashXof(data: Uint8Array, outLen: number): Array<number>

export declare function keyedHash(data: Uint8Array, key: Uint8Array): Array<number>
